config/routes.rb
Swytchat::Application.routes.draw do
 
 mount Resque::Server, :at => "/resque" 

root to: 'rooms#index'
match '/rooms',    to: 'rooms#index', via: :get
match '/activities/active_users', to: 'activities#active_users', via: :get
  
  resources :messages, only: [:create]

  resources :attach_files, only: [:create, :destroy]

    
    resources :rooms do
             get 'sendnew', :on => :member
             get 'tracking', :on => :member
             get 'password_request', :on => :member
             get 'password_check', :on => :member
    end    

  resources :users, only: [:new, :create, :destroy, :show, :index, :edit, :update]

  resources :sessions, only: [:new, :create, :destroy]

  
  match '/about',   to: 'static#about', via: :get
  match '/contact', to: 'static#contact', via: :get
  match '/signin',  to: 'sessions#new', via: :get
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/signup',  to: 'users#new', via: :get

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                  :integer          not null, primary key
#  name                :string(255)
#  string              :string(255)
#  email               :string(255)
#  password_digest     :string(255)
#  remember_token      :string(255)
#  created_at          :datetime
#  updated_at          :datetime
#  avatar_file_name    :string(255)
#  avatar_content_type :string(255)
#  avatar_file_size    :integer
#  avatar_updated_at   :datetime
#

class User < ActiveRecord::Base
attr_accessible :name, :email, :password, :password_confirmation, :change_password
has_attached_file :avatar,
:styles => { :medium => "200x200>", :thumb => "40x40>" },
:default_url => "/images/:style/default_avatar.png"

validates_attachment :avatar, :content_type => {:content_type => /image/ },
:size => {:in => 0..500.kilobytes }


has_secure_password
before_save { email.downcase! }
before_save :create_remember_token

validates :name, presence: true, length: { maximum: 50 },
					uniqueness: { case_sensitive: true }
VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
validates :email, presence:   true,
                  format:     { with: VALID_EMAIL_REGEX },
                  uniqueness: { case_sensitive: false }
validates :password, presence: true, length: { minimum: 6 }, :if => :change_password?
validates :password_confirmation, presence: true, :if => :change_password?


has_many :messages
has_many :rooms
has_many :activities, foreign_key: "user_id"
has_many :attach_file, foreign_key: "user_id"

def change_password=(ch)
    	@change_password = ch
 end


#PRIVATE
private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end

    

    def change_password?
    	@change_password
    end




end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 
before_filter :signed_in_user,
                only: [:index, :show, :edit] 
def new
 @user = User.new
end

def show

  @user = User.find(params[:id])
  @user_registred = @user.created_at.to_formatted_s(:long) 
  @cnt_messages = Message.where("user_id = ?", params[:id]).count
  
  store_location
end


def index
  @users = User.paginate(page: params[:page])
  
end

def edit

  @user = User.find(params[:id])
  if current_user.id!=@user.id
     flash[:error] = "Вы не можете редактировать этого пользователя"
     return redirect_back_or root_path
  end


end


def create
	@user = User.create( user_params )
  
  
	 if @user.save
      flash[:success] = "Добро пожаловать, #{@user.name}"
      sign_in @user
      redirect_to root_path
    else
      render 'new'
    end
end

def update

  @user = User.find_by_id(params[:id])
    if @user.nil? #only author can edit a room
     flash[:error] = "Пользователь не найден"
     return redirect_to root_path
    end

    if @user.id!=current_user.id #only author can edit a room
     flash[:error] = "Вы не можете редактировать этого пользователя"
     return redirect_to root_path
    end


  if params[:chpass]==nil #need change password?
    params[:user].delete :password
    params[:user].delete :password_confirmation
  end

    @user.change_password = params[:chpass] #skip validation flag

    @user.avatar = params[:user][:avatar]

  if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to users_path
    else
      render 'edit'
    end
end  

private

def correct_user
  @user = User.find(params[:id])
  redirect_to(root_path) unless current_user?(@user)
end




 def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.haml
= provide(:title, 'Редактирование информации пользователя')

%h2
  Редактирование профиля


.row
  .span6.offset3
    
    =form_for @user, :html => {:multipart=> true, :autocomplete => "off"} do |f|

      = render "shared/error_messages", object: f.object

      = f.label :name
      = f.text_field :name, autofocus: true

      = f.label :email
      = f.text_field :email

      = f.label 'Загрузить аватар'
      = f.file_field :avatar

      %p

      = check_box_tag 'chpass'
      =f.label 'Изменить пароль', for: 'chpass', class: 'checkbox inline'

      %p

      #div_chpass
        = f.label 'Пароль'
        = f.password_field :password 

        = f.label "Подтверждение" 
        = f.password_field :password_confirmation

      %p 

      = f.submit "Готово", class: "btn btn-primary"
      %button.btn Удалить

app/views/users/index.html.erb
<% provide(:title, 'Пользователи') %>
<h2>Пользователи</h2>

<%= will_paginate %>

<ul class="users">
  <% @users.each do |user| %>
    <li>
    <%= link_to user.name, user_path(user.id), class: "link_black" %>
   </li>
  <% end %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Регистрация пользователя') %>
<h2>Регистрация </h2>

<div class="row">
  <div class="span6 offset3">
    <%= form_for @user, :html => {:autocomplete => "off"} do |f| %>
 <%= render 'shared/error_messages', object: f.object %>
      <%= f.label 'Имя' %> 
      
      <%= f.text_field :name, autofocus: true, placeholder: "Имя будет отображаться при переписке" %>


      <%= f.label 'Почтовый адрес' %>
      <%= f.text_field :email, placeholder: "Можно не указывать настоящий =P" %>

      <%= f.label 'Пароль' %>
      <%= f.password_field :password, placeholder: "6 символов" %>

      <%= f.label 'Еще раз пароль' %>
      <%= f.password_field :password_confirmation, placeholder: "Здесь могла быть ваша реклама"%>

      <%= f.submit "Готово", class: "btn btn-large btn-primary" %>
    <% end %>

   
  </div>
</div>

app/views/users/show.html.haml
=provide :title, @user.name


.row
	%h2
		- if @user.id==current_user.id 
			="Профиль пользователя "
			=link_to @user.name, edit_user_path(@user.id)
		- else
			="Профиль пользователя " + @user.name
		
.row
	%aside.span4
		%section
			=image_tag @user.avatar.url(:medium)
	%aside.span8
		%p
		%p
			="Число сообщений: "
			= @cnt_messages
		%p
			="Дата регистрации: "
			= @user_registred
	
		
		