config/routes.rb
Swytchat::Application.routes.draw do
 
 mount Resque::Server, :at => "/resque" 

root to: 'rooms#index'
match '/rooms',    to: 'rooms#index', via: :get
match '/activities/active_users', to: 'activities#active_users', via: :get
  
  resources :messages, only: [:create]

  resources :attach_files, only: [:create, :destroy]

    
    resources :rooms do
             get 'sendnew', :on => :member
             get 'tracking', :on => :member
             get 'password_request', :on => :member
             get 'password_check', :on => :member
    end    

  resources :users, only: [:new, :create, :destroy, :show, :index, :edit, :update]

  resources :sessions, only: [:new, :create, :destroy]

  
  match '/about',   to: 'static#about', via: :get
  match '/contact', to: 'static#contact', via: :get
  match '/signin',  to: 'sessions#new', via: :get
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/signup',  to: 'users#new', via: :get

end

app/views/shared/_attach_file.html.haml
%div{id:"att_file_container"}
 %div{type: 'button', id: 'btn_display_file', class: 'btn', "data-toggle" => 'collapse', :href => '#attach_file'}
  %i.icon-file

 %div{class: 'collapse', id: 'attach_file'}
  = form_for @attachfile, :url => attach_files_path(room_id: @room.id, user_id: current_user.id), :html => { :multipart => true, :method => :post } do |f|
   =fields_for :files do |f_i|
    =f_i.file_field :file 
    =f.submit "Отправить", class: "btn", id: "attach_send_btn"

       

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_lock_icon.html.erb
<% if (@class == "pass") %>
       <%= image_tag "lock.png", size: @size, alt: "Lock", class: "lock_icon" %>
 <% else%> 
       <%= image_tag "free.png", size: @size, alt: "Lock", class: "lock_icon" %>
 <% end%> 

app/views/shared/_message_form.html.erb
<%= form_for @message, remote: true, html: {'data-type' => 'json'} do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
   
  
    <%= f.text_field :content, placeholder: "Пиши сообщение здесь и жми Enter", autofocus: true, autocomplete: :off, class: "mes-input" %>
    
<% end %>