config/routes.rb
Swytchat::Application.routes.draw do
 
 mount Resque::Server, :at => "/resque" 

root to: 'rooms#index'
match '/rooms',    to: 'rooms#index', via: :get
match '/activities/active_users', to: 'activities#active_users', via: :get
  
  resources :messages, only: [:create]

  resources :attach_files, only: [:create, :destroy]

    
    resources :rooms do
             get 'sendnew', :on => :member
             get 'tracking', :on => :member
             get 'password_request', :on => :member
             get 'password_check', :on => :member
    end    

  resources :users, only: [:new, :create, :destroy, :show, :index, :edit, :update]

  resources :sessions, only: [:new, :create, :destroy]

  
  match '/about',   to: 'static#about', via: :get
  match '/contact', to: 'static#contact', via: :get
  match '/signin',  to: 'sessions#new', via: :get
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/signup',  to: 'users#new', via: :get

end

app/models/room.rb
# == Schema Information
#
# Table name: rooms
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  password_digest :string(255)
#  created_at      :datetime
#  updated_at      :datetime
#  no_pass         :boolean          default(FALSE)
#  salt            :string(255)
#  remember_token  :string(255)
#  users           :text
#  user_id         :integer
#

class Room < ActiveRecord::Base

  attr_accessible :name, :password, :password_confirmation

  has_secure_password :validations => false

belongs_to :user

has_many :messages, dependent: :destroy

  validates :password, presence: true, confirmation: true, :if => :setting_password?
  validates :password_confirmation, presence: true        , :if => :setting_password?

  validates :name, length: { maximum: 50 }, presence: true,
					uniqueness: {case_sensitive: false}
 has_many :activities, foreign_key: "room_id", dependent: :destroy
 has_many :attach_file, foreign_key: "room_id", dependent: :destroy
 has_many :active_users, :through => :activities

##def authenticate(password)
 ##   password.present? && password_digest.present? && password_digest == BCrypt::Engine.hash_secret(password, password_salt)
##end

#def no_pass?
 #    if password=""
  #   	no_pass=true
  #   end
  #end



private

   
def setting_password?
    password.present? || password_confirmation.present?
end





end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
 before_filter :signed_in_user
                    
 before_filter :only_owner,
                only: [:edit, :destroy, :update]

def destroy
   @room = Room.find(params[:id])
   @room.destroy
   if @room.save
    flash[:success] = "Комната удалена"
    redirect_to rooms_path
   else
    flash[:error] = "Неудача"
    render 'edit'
    end

end

  
def edit

  @room = Room.find(params[:id])
end

def update

if params[:chpass] #was password changed?
  @room.remember_token = create_remember_token
  params[:room][:password].blank? ? @room.no_pass = true : @room.no_pass = false
end

  if @room.update_attributes(params[:room])
    flash[:success] = "Обновлено!"
   redirect_to room_path
  else
    render 'edit'
  end
end  


  def new
  	@room = Room.new
  end

def index
      @rooms = Room.paginate(page: params[:page])
  end
def password_request


end

def password_check
  room = Room.find(params[:id])
   if (room && room.authenticate(params[:room][:password].to_s))
     save_room_token room
     redirect_to room_path (room)
   else
      flash[:error] = 'Неверный пароль'
      redirect_to password_request_room_path(room)
    end

end



  def show
    store_location
    @room = Room.find(params[:id])
    @attachfile = @room.attach_file.build

        
          if !check_room_token(@room.id) then
            redirect_to password_request_room_path(@room)
           end
        

        session[:room_id] = @room.id
       @messages = @room.messages
        @message = Message.new
  end
  

def create
 @room = current_user.rooms.build( params[:room] )
 @room.remember_token = create_remember_token
  @room.password.blank? ? @room.no_pass = true : @room.no_pass = false
   if @room.save
    flash[:success] = "Добро пожаловать в #{@room.name}"
     redirect_to room_path @room.id
    else
     render 'new'
    end
end

def sendnew

 @date_from = date_from(params[:period])
 
 if !check_room_token(params[:room_id].to_i) then 
  render :json=> "Доступ запрещен"
  return
 end 

  @messages = Message.where("room_id = ? AND id > ? AND created_at >= ?",
   params[:room_id], params[:last_message_id], @date_from)
      
  respond_to do |format|
      format.json { 
          render :json=>@messages.map { 
          |message| 
            {
            :id => message.id,
            :name => message.user.name,
            :content => message.content,
            :time => message.created_at.strftime("%d-%m-%Y %H:%M:%S") }
            }
      }
    end
end



end

app/helpers/rooms_helper.rb
module RoomsHelper

	def save_room_token (room)
		
		cookies.permanent["#{room.id}token"]= { :value => room.remember_token, :expires => Time.now + 3600}
	end

	def check_room_token(id)
		if Room.find_by_id(id).no_pass then
		 return true 
		end
		@r = Room.find_by_remember_token(cookies["#{id}token"])
		return ( !@r.nil? && @r.id == id)
	end

def create_remember_token
      return remember_token = SecureRandom.urlsafe_base64
    end

def only_owner
	if !is_owner?
		flash[:error] = "Нет прав"
     	redirect_back_or root_path
    end
end


def is_owner?
 @room = current_user.rooms.find_by_id(params[:id])
    if @room.nil? #only author can edit a room
    	return false
    else
    	return true
    end
end


	def date_from (period)

		case period
		when '1'
		    return 1.day.ago
		when '2'
		    return 1.week.ago
		when '3'
		    return 1.month.ago
		when '4'
		    return 100.year.ago
		else
		    return 1.week.ago
		end
	end


	def ClearOld (json)
		return ''
	end

end

app/views/rooms/edit.html.haml
%h2
  Редактирование комнаты

.row
  .span6.offset3
    = form_for(@room) do |f| 
      =render 'shared/error_messages', object: f.object 
      =f.label 'Название:'
      =f.text_field :name

      %p
     
      = check_box_tag 'chpass'
      =f.label 'Изменть пароль', for: 'chpass', class: 'checkbox inline'

      %p

      #div_chpass
        = f.label 'Пароль'
        = f.password_field :password 

        = f.label "Подтверждение" 
        = f.password_field :password_confirmation  

      =f.submit "Сохранить", class: "btn btn-primary"
      =link_to ' Удалить комнату', @room, method: 'delete'
      
    
   

   

app/views/rooms/index.html.erb
<% provide(:title, 'Список комнат') %>

 


<h2>Комнаты</h2>

<%= will_paginate %>

<ul class="rooms">
  <% @rooms.each do |room| %>
    <li>
  <%  room.no_pass ? @class = "free" : @class = "pass" %>
   <% @size = '18' %>
   <%= render 'shared/lock_icon' %>
   <%= link_to room.name, {:controller => "rooms", :action =>"show", :id => room.id}, :class => @class+" link_black"
   %>

</li>
  <% end %>
</ul>

<%= will_paginate %>

app/views/rooms/new.html.erb
<% provide(:title, 'Sign up') %>

<h2>Создать комнату</h2>

<div class="row">
  <div class="span6 offset3">
    <%= form_for @room, :html => {:autocomplete => "off"} do |f| %>
      
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name, 'Название'%>
      <%= f.text_field :name, autofocus: true   %>
    
      <%= f.label :password, 'Пароль для входа в комнату'%>
      <%= f.password_field :password, placeholder: "Можно и без пароля"  %>

      <%= f.label :password_confirmation, "Повторите пароль" %>
      <%= f.password_field :password_confirmation, placeholder: "Цемент недорого. 8(931) 1234567. Павел"  %>

      <%= f.submit "Создать комнату", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/rooms/password_check.html.erb
<% provide(:title, "Check password") %>

</div>

app/views/rooms/password_request.html.erb
<% provide(:title, "Room password") %>
<h2>Введите пароль для входа в комнату</h2>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(:room, url: password_check_room_path, method: 'get') do |f| %>
     
      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.submit "Sign in", class: "btn btn-large btn-primary" %>
    <% end %>

     <p> Я не знаю пароль и хочу перейти<%= link_to " обратно к списку комнат", rooms_path %></p>
  </div>
</div>

app/views/rooms/show.html.erb
<% provide(:title, @room.name) %>



 <script>
  last_message_id = 0;
  focused = true;
  period = 1;
  $(document).ready(function(){
     room_id = <%= @room.id %>
     get_messages();
     get_users();
     new_messages_check();
     users_check();
     oldTitle = document.title;
     });
  </script>

  <div class="row">
    <h2>
      <% @room.no_pass ? @class = "free" : @class = "pass" %>
      <% @size = '21'%>
      <%= render 'shared/lock_icon' %>
        <% if current_user.id == @room.user_id
          concat link_to @room.name,  {:controller => "rooms", :action =>"edit", :id => @room.id}, class: 'link_black'
            
         else
            concat @room.name
         end%>
    </h2>
  </div>

<div class="row">
            
    <div class="span9">
      <%= render 'shared/message_form' %>
      <%= render 'shared/attach_file' %>
        <div class="history btn-group pull-center" data-toggle="buttons-radio">
          <button class="btn btn-mini active" id="btn_day" data-toggle="button">День</button>
          <button class="btn btn-mini" id="btn_week" data-toggle="button">Неделя</button>
          <button class="btn btn-mini" id = "btn_month" data-toggle="button">Месяц</button>
          <button class="btn btn-mini" id = "btn_all" data-toggle="button">Все</button>
        </div>  
       
      <ol class="messages"></ol>
    </div>
  <div class="span3">
    <div id="room_info">
      <h3>Сейчас в комнате</h3>
          <ol class="users"></ol>
    </div>
  </div>
</div>