config/routes.rb
Swytchat::Application.routes.draw do
 
 mount Resque::Server, :at => "/resque" 

root to: 'rooms#index'
match '/rooms',    to: 'rooms#index', via: :get
match '/activities/active_users', to: 'activities#active_users', via: :get
  
  resources :messages, only: [:create]

  resources :attach_files, only: [:create, :destroy]

    
    resources :rooms do
             get 'sendnew', :on => :member
             get 'tracking', :on => :member
             get 'password_request', :on => :member
             get 'password_check', :on => :member
    end    

  resources :users, only: [:new, :create, :destroy, :show, :index, :edit, :update]

  resources :sessions, only: [:new, :create, :destroy]

  
  match '/about',   to: 'static#about', via: :get
  match '/contact', to: 'static#contact', via: :get
  match '/signin',  to: 'sessions#new', via: :get
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/signup',  to: 'users#new', via: :get

end

app/views/layouts/_footer.html.erb
<footer class="footer">
   <nav>
    <ul>
      <li><%= link_to "О проекте",   about_path %></li>
      <li><%= link_to "Контакты", contact_path %></li>
      </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
  
      
      <%= link_to "Swyttalk", root_path, id: "logo" %>
    
     <nav>
        <ul class="nav nav-pills pull-right"> 

          <% if signed_in? %>

              <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                           <li><%= link_to "Пользователи", users_path%></li>
                        <b class="caret"></b>
                    </a>
              </li>
              
               <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                           Комнаты
                        <b class="caret"></b>
                    </a>
                        <ul class="dropdown-menu">
                              <li><%= link_to "Создать", new_room_path%></li>
                              <li><%= link_to "Все комнаты", rooms_path%></li>
                        </ul>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <%= session[:user_name] %>
                    <b class="caret"></b>
                </a>
                    <ul class="dropdown-menu">
                          <li><%= link_to "Мой профиль", edit_user_path(current_user.id) %>
                          <li><%= link_to "Выход", signout_path, method: :delete %>
                    </ul>
                </li>


            
            </li>

         </div>
        <% else %>
           <li><%= link_to "Вход", signin_path %></li>
          <% end %>
        </ul>
        
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_ie.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/ie' %>
  </head>
      <body>
  <%=   render 'layouts/header'%>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
 
    </div>

     <%= debug(params) if Rails.env.development? %>
  </body>
</html>